package com.redline.worldcore.server.pregen;

import com.redline.worldcore.api.cube.CubeStatus;
import com.redline.worldcore.api.pos.CubePos;

/** Immutable debug snapshot for commands and client overlay. */
public record CubePregenSnapshot(
        boolean running,
        boolean paused,
        int queuedCubes,
        long activeTotalCubes,
        long activeProcessedCubes,
        long totalStartedJobs,
        long totalCompletedJobs,
        long totalProcessedCubes,
        long totalGeneratedCubes,
        long totalSkippedCubes,
        long totalFailedCubes,
        int lastTickProcessed,
        int lastTickGenerated,
        int lastTickSkipped,
        int lastTickFailed,
        long lastTickMicros,
        long maxTickMicros,
        int maxCubesPerTick,
        int maxMillisPerTick,
        int maxSkippedCubesPerTick,
        int maxGeneratedCubesPerSecond,
        int expensiveCubeMillis,
        int cooldownAfterExpensiveTicks,
        int throttleCooldownTicks,
        int generatedThisSecond,
        String throttleReason,
        CubeStatus targetStatus,
        CubePos activeMin,
        CubePos activeMax,
        String activeJobId,
        String activeOwner,
        String lastError,
        int visitedColumns,
        int backfillDoneColumns,
        boolean backfillEnabled,
        int backfillPendingColumns,
        long backfillJobsStarted,
        int backfillMaxVerticalRadius,
        int backfillDelayTicks,
        String backfillTargetStatus,
        String backfillLastReason,
        boolean afkEnabled,
        int afkTrackedPlayers,
        int afkPlayers,
        long afkJobsStarted,
        int afkAfterTicks,
        int afkRadiusBlocks,
        int afkVerticalRadiusCubes,
        String afkTargetStatus,
        String afkLastReason
) {
    public static CubePregenSnapshot empty(CubePregenBudget budget) {
        return new CubePregenSnapshot(
                false,
                false,
                0,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0,
                0,
                0,
                0,
                0L,
                0L,
                budget.maxCubesPerTick(),
                budget.maxMillisPerTick(),
                budget.maxSkippedCubesPerTick(),
                budget.maxGeneratedCubesPerSecond(),
                budget.expensiveCubeMillis(),
                budget.cooldownAfterExpensiveTicks(),
                0,
                0,
                "idle",
                CubeStatus.EMPTY,
                null,
                null,
                "none",
                "none",
                "",
                0,
                0,
                false,
                0,
                0L,
                0,
                0,
                CubeStatus.EMPTY.name(),
                "idle",
                false,
                0,
                0,
                0L,
                0,
                0,
                0,
                CubeStatus.EMPTY.name(),
                "idle"
        );
    }

    public long remainingCubes() {
        return Math.max(0L, activeTotalCubes - activeProcessedCubes);
    }
}
